"""create inital tables

Revision ID: d4629e0c0faa
Revises: c27215297923
Create Date: 2025-11-19 16:31:30.229738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4629e0c0faa'
down_revision: Union[str, Sequence[str], None] = 'c27215297923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('trigger', sa.Enum('MANUAL', 'SCHEDULED', name='jobtrigger'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_history_id'), 'job_history', ['id'], unique=False)
    op.create_index(op.f('ix_job_history_job_id'), 'job_history', ['job_id'], unique=True)
    op.create_table('weather_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('wind_speed', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_data_city'), 'weather_data', ['city'], unique=True)
    op.create_index(op.f('ix_weather_data_id'), 'weather_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_data_id'), table_name='weather_data')
    op.drop_index(op.f('ix_weather_data_city'), table_name='weather_data')
    op.drop_table('weather_data')
    op.drop_index(op.f('ix_job_history_job_id'), table_name='job_history')
    op.drop_index(op.f('ix_job_history_id'), table_name='job_history')
    op.drop_table('job_history')
    # ### end Alembic commands ###
